import {DropdownOption} from '~/components'

const _generateOptions = (...titles : string[]) : DropdownOption[] => 
  titles.map((title) => ({title, value: title.toLowerCase()}))

export const MODE_OPTIONS = _generateOptions('Normal', 'Diff')
export const ACCESS_OPTIONS = _generateOptions('Public', 'Unlisted')
export const SYNTAX_OPTIONS = _generateOptions(
  'Plain Text',
  'Bash',
  'Brainfuck',
  'C',
  'CPP',
  'CSS',
  'Clojure',
  'Cobol',
  'Crystal',
  'Csharp',
  'Dart',
  'Diff',
  'Docker',
  'Elixir',
  'Fortran',
  'Go',
  'Graphql',
  'Groovy',
  'HTML',
  'Haskell',
  'JSX',
  'Java',
  'Javascript',
  'Json',
  'Kotlin',
  'Lua',
  'Makefile',
  'Markdown',
  'ObjectiveC',
  'PHP',
  'Perl',
  'Powershell',
  'Prolog',
  'Python',
  'R',
  'Regex',
  'Ruby',
  'Rust',
  'SQL',
  'Sass',
  'Scala',
  'Scheme',
  'SCSS',
  'Solidity',
  'Swift',
  'TSX',
  'Typescript',
  'Vim',
  'Wasm'
)
